version: '3.8'

services:
  securechat-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=test
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3